# Generated by Django 5.1.5 on 2025-04-15 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nivel',
            new_name='role',
        ),
    ]
